### ISSUE TITLE
Targeting html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [clayakers/Dasmoto-Project#3]
Nothing wrong with using html to set styles for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/clayakers/Dasmoto-Project/blob/master/resources/css/style.css#L1-L3

**Comment by clayakers** [comment]
Thanks for the article! I will bookmark it for later reference as I create more pages with CSS.
